### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by trebmuh** [x42/midimap.lv2#1]
Hi again Robin,
Is there any user case documentation somewhere? I quickly checked x42-plugins.com but didn't find nothing.

**Comment by x42** [comment]
https://github.com/x42/midimap.lv2/blob/master/cfg/doc.cfg

is as best as it gets for now

**Comment by rschwarz** [comment]
I tried loading the plugin in Carla and could select one of the 8 presets. But it's not clear how I can load my custom `cfg` file. Should it be in a specific path?

**Comment by x42** [comment]
You probably need a recent version of Carla that offers a file-selector.
@falktx : Which version of Carla added support for Patch Set/Get?

**Comment by rschwarz** [comment]
Thanks for the quick reply.
For reference: I'm using Carla 2.0.0 from the kxstudio repos.
This is what the GUI looks like for me:
![screenshot](https://i.imgur.com/yi3nMLs.png)
Saving the state seems to be disabled, and loading state offers me to select one of the presets.

I also (quickly) tried the `carla-git` package, which has version 2.0.90, but it shows the same behavior (only the preset names are missing now).

**Comment by rschwarz** [comment]
I'm still ignorant about LV2 internals, but I guess I could create my own plugin consisting of presets for Midi Event Map?

**Comment by x42** [comment]
I don't know Carla. With jalv, Qtractor or Ardour there's a file-selector to pick a file...

**Comment by x42** [comment]
Maybe load it in jalv. and then save a preset for using it with Carla?
![image](https://user-images.githubusercontent.com/30246/69905765-b207fe80-13b8-11ea-9793-66fcce6eb043.png)

**Comment by rschwarz** [comment]
Thanks, I will try with jalv and ardour.

**Comment by x42** [comment]
Above screenshot is from

```
jalv.gtk http://gareus.org/oss/lv2/midimap
```

**Comment by rschwarz** [comment]
Good, `jalv` also works for me :tada:

**Comment by falkTX** [comment]
You need latest version of carla, aka "carla-git".
The plugin-gui button changes into a file open button if the plugin has no custom gui and can handle files.

Carla 2.0 does not support this.
